# GLAUCOMA

In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go 

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("glaucoma.csv")

In [5]:
df.head()

Patient ID  Age  Gender Visual Acuity Measurements  \
0       62431   69    Male                 LogMAR 0.1   
1       68125   69  Female                 LogMAR 0.1   
2       63329   67  Female                      20/40   
3       47174   23    Male                 LogMAR 0.0   
4       67361   21    Male                 LogMAR 0.1   

   Intraocular Pressure (IOP)  Cup-to-Disc Ratio (CDR) Family History  \
0                       19.46                     0.42             No   
1                       18.39                     0.72             No   
2                       23.65                     0.72             No   
3                       18.04                     0.61             No   
4                       15.87                     0.30             No   

  Medical History                                   Medication Usage  \
0        Diabetes  Amoxicillin, Lisinopril, Omeprazole, Atorvasta...   
1    Hypertension  Lisinopril, Amoxicillin, Atorvastatin, Ibuprof...   
2    Hypertension  Amoxicillin, Ibuprofen, Metformin, Atorvastati...   
3             NaN                                 Ibuprofen, Aspirin   
4        Diabetes  Amoxicillin, Omeprazole, Aspirin, Ibuprofen, A...   

              Visual Field Test Results  \
0  Sensitivity: 0.54, Specificity: 0.75   
1  Sensitivity: 0.72, Specificity: 0.88   
2   Sensitivity: 0.56, Specificity: 0.8   
3   Sensitivity: 0.6, Specificity: 0.93   
4   Sensitivity: 0.82, Specificity: 0.9   

          Optical Coherence Tomography (OCT) Results  Pachymetry  \
0  RNFL Thickness: 86.48 µm, GCC Thickness: 64.14...      541.51   
1  RNFL Thickness: 96.88 µm, GCC Thickness: 56.48...      552.77   
2  RNFL Thickness: 89.81 µm, GCC Thickness: 59.05...      573.65   
3  RNFL Thickness: 87.25 µm, GCC Thickness: 63.98...      590.67   
4  RNFL Thickness: 82.61 µm, GCC Thickness: 66.01...      588.41   

  Cataract Status Angle Closure Status  \
0         Present                 Open   
1          Absent                 Open   
2          Absent               Closed   
3          Absent               Closed   
4          Absent               Closed   

                                     Visual Symptoms    Diagnosis  \
0                    Tunnel vision, Eye pain, Nausea  No Glaucoma   
1     Redness in the eye, Vision loss, Tunnel vision  No Glaucoma   
2  Halos around lights, Vision loss, Redness in t...  No Glaucoma   
3                Nausea, Nausea, Halos around lights  No Glaucoma   
4                  Eye pain, Eye pain, Tunnel vision  No Glaucoma   

                 Glaucoma Type  
0  Primary Open-Angle Glaucoma  
1            Juvenile Glaucoma  
2            Juvenile Glaucoma  
3          Congenital Glaucoma  
4  Primary Open-Angle Glaucoma

In [6]:
df.tail()

Patient ID  Age  Gender Visual Acuity Measurements  \
9995       61720   81  Female                 LogMAR 0.1   
9996       34983   65    Male                 LogMAR 0.0   
9997       67810   56  Female                      20/40   
9998       34285   26    Male                 LogMAR 0.1   
9999       85320   76    Male                 LogMAR 0.0   

      Intraocular Pressure (IOP)  Cup-to-Disc Ratio (CDR) Family History  \
9995                       22.83                     0.49             No   
9996                       11.72                     0.54             No   
9997                       10.67                     0.56            Yes   
9998                       23.37                     0.74             No   
9999                       22.90                     0.50             No   

         Medical History                    Medication Usage  \
9995                 NaN                                 NaN   
9996            Diabetes                          Lisinopril   
9997            Diabetes                           Ibuprofen   
9998  Glaucoma in family                                 NaN   
9999            Diabetes  Lisinopril, Ibuprofen, Amoxicillin   

                 Visual Field Test Results  \
9995  Sensitivity: 0.81, Specificity: 0.97   
9996   Sensitivity: 0.7, Specificity: 0.97   
9997    Sensitivity: 0.8, Specificity: 0.9   
9998   Sensitivity: 0.68, Specificity: 0.9   
9999  Sensitivity: 0.87, Specificity: 0.73   

             Optical Coherence Tomography (OCT) Results  Pachymetry  \
9995  RNFL Thickness: 83.41 µm, GCC Thickness: 66.55...      576.53   
9996  RNFL Thickness: 83.04 µm, GCC Thickness: 63.24...      548.10   
9997  RNFL Thickness: 95.93 µm, GCC Thickness: 59.78...      513.74   
9998  RNFL Thickness: 92.84 µm, GCC Thickness: 69.35...      585.03   
9999  RNFL Thickness: 88.77 µm, GCC Thickness: 58.74...      510.10   

     Cataract Status Angle Closure Status  \
9995          Absent                 Open   
9996          Absent                 Open   
9997         Present                 Open   
9998          Absent               Closed   
9999          Absent                 Open   

                              Visual Symptoms    Diagnosis  \
9995        Eye pain, Eye pain, Tunnel vision     Glaucoma   
9996  Eye pain, Halos around lights, Vomiting  No Glaucoma   
9997    Vision loss, Vomiting, Blurred vision  No Glaucoma   
9998      Halos around lights, Nausea, Nausea     Glaucoma   
9999  Eye pain, Eye pain, Halos around lights     Glaucoma   

                Glaucoma Type  
9995  Normal-Tension Glaucoma  
9996  Normal-Tension Glaucoma  
9997       Secondary Glaucoma  
9998  Normal-Tension Glaucoma  
9999        Juvenile Glaucoma

In [7]:
df.shape

(10000, 17)

In [8]:
df.columns

Index(['Patient ID', 'Age', 'Gender', 'Visual Acuity Measurements',
       'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)',
       'Family History', 'Medical History', 'Medication Usage',
       'Visual Field Test Results',
       'Optical Coherence Tomography (OCT) Results', 'Pachymetry',
       'Cataract Status', 'Angle Closure Status', 'Visual Symptoms',
       'Diagnosis', 'Glaucoma Type'],
      dtype='object')

In [9]:
df.duplicated().sum()

0

In [10]:
df.isnull().sum()

Patient ID                                       0
Age                                              0
Gender                                           0
Visual Acuity Measurements                       0
Intraocular Pressure (IOP)                       0
Cup-to-Disc Ratio (CDR)                          0
Family History                                   0
Medical History                               2547
Medication Usage                              1231
Visual Field Test Results                        0
Optical Coherence Tomography (OCT) Results       0
Pachymetry                                       0
Cataract Status                                  0
Angle Closure Status                             0
Visual Symptoms                                  0
Diagnosis                                        0
Glaucoma Type                                    0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Patient ID                                  10000 non-null  int64  
 1   Age                                         10000 non-null  int64  
 2   Gender                                      10000 non-null  object 
 3   Visual Acuity Measurements                  10000 non-null  object 
 4   Intraocular Pressure (IOP)                  10000 non-null  float64
 5   Cup-to-Disc Ratio (CDR)                     10000 non-null  float64
 6   Family History                              10000 non-null  object 
 7   Medical History                             7453 non-null   object 
 8   Medication Usage                            8769 non-null   object 
 9   Visual Field Test Results                   10000 non-null  object 
 10  Optical Coh

In [12]:
df.describe()

Patient ID           Age  Intraocular Pressure (IOP)  \
count  10000.00000  10000.000000                10000.000000   
mean   50002.16880     53.872200                   17.507527   
std    28939.82498     21.127563                    4.356101   
min        4.00000     18.000000                   10.000000   
25%    24660.25000     36.000000                   13.760000   
50%    50091.50000     54.000000                   17.485000   
75%    74829.25000     72.000000                   21.300000   
max    99992.00000     90.000000                   25.000000   

       Cup-to-Disc Ratio (CDR)    Pachymetry  
count             10000.000000  10000.000000  
mean                  0.548437    549.733974  
std                   0.144326     28.902741  
min                   0.300000    500.010000  
25%                   0.420000    524.590000  
50%                   0.550000    549.335000  
75%                   0.670000    574.972500  
max                   0.800000    599.990000

In [13]:
df.nunique()

Patient ID                                    10000
Age                                              73
Gender                                            2
Visual Acuity Measurements                        4
Intraocular Pressure (IOP)                     1499
Cup-to-Disc Ratio (CDR)                          51
Family History                                    2
Medical History                                   3
Medication Usage                               4079
Visual Field Test Results                      1574
Optical Coherence Tomography (OCT) Results    10000
Pachymetry                                     6343
Cataract Status                                   2
Angle Closure Status                              2
Visual Symptoms                                 512
Diagnosis                                         2
Glaucoma Type                                     6
dtype: int64

In [14]:
def classify_features(df):
    categorical_features = []
    non_categorical_features = []
    discrete_features = []
    continuous_features = []

    for column in df.columns:
        if df[column].dtype in ['object','bool']:
            if df[column].nunique() < 10:
                categorical_features.append(column)
            else:
                non_categorical_features.append(column)
        elif df[column].dtype in ['int64', 'float64']:
            if df[column].nunique() < 10:
                discrete_features.append(column)
            else:
                continuous_features.append(column)

    return categorical_features, non_categorical_features, discrete_features, continuous_features

In [15]:
categorical, non_categorical, discrete, continuous = classify_features(df)

In [16]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Visual Acuity Measurements', 'Family History', 'Medical History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis', 'Glaucoma Type']
Non-Categorical Features: ['Medication Usage', 'Visual Field Test Results', 'Optical Coherence Tomography (OCT) Results', 'Visual Symptoms']
Discrete Features: []
Continuous Features: ['Patient ID', 'Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']


In [17]:
df = df.drop(['Patient ID','Medication Usage', 'Visual Field Test Results', 'Optical Coherence Tomography (OCT) Results', 'Visual Symptoms'],axis=1)

In [18]:
df.isnull().sum()

Age                              0
Gender                           0
Visual Acuity Measurements       0
Intraocular Pressure (IOP)       0
Cup-to-Disc Ratio (CDR)          0
Family History                   0
Medical History               2547
Pachymetry                       0
Cataract Status                  0
Angle Closure Status             0
Diagnosis                        0
Glaucoma Type                    0
dtype: int64

In [19]:
df =df.drop(['Medical History'],axis=1)

In [20]:
df

Age  Gender Visual Acuity Measurements  Intraocular Pressure (IOP)  \
0      69    Male                 LogMAR 0.1                       19.46   
1      69  Female                 LogMAR 0.1                       18.39   
2      67  Female                      20/40                       23.65   
3      23    Male                 LogMAR 0.0                       18.04   
4      21    Male                 LogMAR 0.1                       15.87   
...   ...     ...                        ...                         ...   
9995   81  Female                 LogMAR 0.1                       22.83   
9996   65    Male                 LogMAR 0.0                       11.72   
9997   56  Female                      20/40                       10.67   
9998   26    Male                 LogMAR 0.1                       23.37   
9999   76    Male                 LogMAR 0.0                       22.90   

      Cup-to-Disc Ratio (CDR) Family History  Pachymetry Cataract Status  \
0                        0.42             No      541.51         Present   
1                        0.72             No      552.77          Absent   
2                        0.72             No      573.65          Absent   
3                        0.61             No      590.67          Absent   
4                        0.30             No      588.41          Absent   
...                       ...            ...         ...             ...   
9995                     0.49             No      576.53          Absent   
9996                     0.54             No      548.10          Absent   
9997                     0.56            Yes      513.74         Present   
9998                     0.74             No      585.03          Absent   
9999                     0.50             No      510.10          Absent   

     Angle Closure Status    Diagnosis                Glaucoma Type  
0                    Open  No Glaucoma  Primary Open-Angle Glaucoma  
1                    Open  No Glaucoma            Juvenile Glaucoma  
2                  Closed  No Glaucoma            Juvenile Glaucoma  
3                  Closed  No Glaucoma          Congenital Glaucoma  
4                  Closed  No Glaucoma  Primary Open-Angle Glaucoma  
...                   ...          ...                          ...  
9995                 Open     Glaucoma      Normal-Tension Glaucoma  
9996                 Open  No Glaucoma      Normal-Tension Glaucoma  
9997                 Open  No Glaucoma           Secondary Glaucoma  
9998               Closed     Glaucoma      Normal-Tension Glaucoma  
9999                 Open     Glaucoma            Juvenile Glaucoma  

[10000 rows x 11 columns]

In [21]:
categorical, non_categorical, discrete, continuous = classify_features(df)

In [22]:
print("Categorical Features:", categorical)
print("Non-Categorical Features:", non_categorical)
print("Discrete Features:", discrete)
print("Continuous Features:", continuous)

Categorical Features: ['Gender', 'Visual Acuity Measurements', 'Family History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis', 'Glaucoma Type']
Non-Categorical Features: []
Discrete Features: []
Continuous Features: ['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']


In [23]:
df= pd.get_dummies(df,columns=['Gender', 'Visual Acuity Measurements', 'Family History', 'Cataract Status', 'Angle Closure Status', 'Diagnosis'],drop_first=False)

In [24]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
df[['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']]=scalar.fit_transform(df[['Age', 'Intraocular Pressure (IOP)', 'Cup-to-Disc Ratio (CDR)', 'Pachymetry']])

In [29]:
df['Glaucoma Type'].value_counts()

Glaucoma Type
Juvenile Glaucoma              1734
Normal-Tension Glaucoma        1699
Primary Open-Angle Glaucoma    1668
Secondary Glaucoma             1657
Congenital Glaucoma            1641
Angle-Closure Glaucoma         1601
Name: count, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from imblearn.over_sampling import RandomOverSampler

In [27]:
from imblearn.over_sampling import SMOTE


In [30]:
X=df.drop('Glaucoma Type',axis=1)
y=df['Glaucoma Type']
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y
)
print("Before Oversampling:",y_train.value_counts())

Before Oversampling: Glaucoma Type
Juvenile Glaucoma              1387
Normal-Tension Glaucoma        1359
Primary Open-Angle Glaucoma    1334
Secondary Glaucoma             1326
Congenital Glaucoma            1313
Angle-Closure Glaucoma         1281
Name: count, dtype: int64


In [31]:
ros=RandomOverSampler(random_state=42)
X_train_res,y_train_res=ros.fit_resample(X_train,y_train)
print("After Oversampling:",y_train_res.value_counts())

After Oversampling: Glaucoma Type
Juvenile Glaucoma              1387
Primary Open-Angle Glaucoma    1387
Secondary Glaucoma             1387
Angle-Closure Glaucoma         1387
Congenital Glaucoma            1387
Normal-Tension Glaucoma        1387
Name: count, dtype: int64


In [32]:
log_res_model = LogisticRegression(max_iter=1000,solver='liblinear')
log_res_model.fit(X_train_res,y_train_res)

LogisticRegression(max_iter=1000, solver='liblinear')

In [34]:
y_pred=log_res_model.predict(X_test)

In [35]:
print("\nAccuracy:",accuracy_score(y_test,y_pred))
print("\nConfussion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nClassfication Report:\n",classification_report(y_test,y_pred))


Accuracy: 0.149

Confussion Matrix:
 [[47 51  8 87 64 63]
 [42 50 13 83 70 70]
 [55 68 17 80 67 60]
 [45 69 20 61 73 72]
 [47 70 18 81 60 58]
 [49 62 22 72 63 63]]

Classfication Report:
                              precision    recall  f1-score   support

     Angle-Closure Glaucoma       0.16      0.15      0.16       320
        Congenital Glaucoma       0.14      0.15      0.14       328
          Juvenile Glaucoma       0.17      0.05      0.08       347
    Normal-Tension Glaucoma       0.13      0.18      0.15       340
Primary Open-Angle Glaucoma       0.15      0.18      0.16       334
         Secondary Glaucoma       0.16      0.19      0.18       331

                   accuracy                           0.15      2000
                  macro avg       0.15      0.15      0.14      2000
               weighted avg       0.15      0.15      0.14      2000

